strategy("RSI Mean Reversion Strategy 2021",
    shorttitle="pinescriptmastery.com", 
    overlay=true, 
    initial_capital=10000, 
    default_qty_value=10000)

rsline = input(title="RSI Length", type=input.integer, defval=14)
rsiOS = input(title="RSI OS", type=input.float, defval=30.0)
rsiSell = input(title="RSI Sell", type=input.float, defval=50.0)
slType = input(title="Stop Loss ATR / %", type=input.bool, defval=true)
slType = input(title="SL Multiplier", type=input.float, defval=1.0, step=0.1)
minimumProfitPercent = input(title="Minimum Profit %", type=input.float, defval=0.00)

atr = atr(14)
rsi = rsi(close, rsilen)

var entry = 0.0
distanceProfitPercent = distanceProfit / entry

profitSignal = minimumProfitPercent == 0.0 or distanceProfitPercent >= minimumProfitPercent
longSignal = rsi <= rsiOS and barstate.isconfirmed and strategy.position_size == 0 and not na(atr)
exitSignal = profitSignal and barstate.isconfirmed and strategy.position_size != 0 and rsi >= rsiSell

longStop = lowest(low, 4) - (atr * slMulti)
longStopPercent = close - (close * slMulti)


var longStopSaved = 0.0
var longTargetgetSaved = 0.0
enterLong = false
if longSignal
    longStopSaved := slType ? longStop : longStopPercent
    enterLong := true
    entry := close

strategy.entry(id="Long",
    long=strategy.long,
    when=enterLong,
    comment="{}")

strategy.exit(id="Long Exit",
    from_entry = "Long",
    limit=exitSignal ? close : na,
    stop=longStopSaved,
    when=strategy.position_size > 0,
    comment="{}")

    plot(strategy position_size > 0 ? longStopSaved : na, color=color.red, style=plot.style_linebr)
    plot(strategy.position_size > 0 ? entry : na, color=color.blue, style=plot.style_linebr)
